---
- name: Disable persistent boot override
  community.general.redfish_command:
    category: Systems
    command: DisableBootOverride
    resource_id: "{{ oob_system_id }}"
    baseuri: "{{ _oob_baseuri_effective }}"
    username: "{{ oob_user }}"
    password: "{{ oob_password }}"
    timeout: "{{ oob_timeout }}"
    validate_certs: "{{ oob_validate_certs }}"
    ca_path: "{{ (oob_ca_path | length > 0) | ternary(oob_ca_path, omit) }}"
  register: _rf_boot_disable
  no_log: "{{ oob_no_log }}"
