---
- name: Disable persistent boot override
  community.general.redfish_command:
    category: Systems
    command: DisableBootOverride
    resource_id: "{{ oob_redfish_control_system_id }}"
    baseuri: "{{ _oob_baseuri_effective }}"
    username: "{{ oob_redfish_control_user }}"
    password: "{{ oob_redfish_control_password }}"
    timeout: "{{ oob_redfish_control_timeout }}"
    validate_certs: "{{ oob_redfish_control_validate_certs }}"
    ca_path: "{{ (oob_redfish_control_ca_path | length > 0) | ternary(oob_redfish_control_ca_path, omit) }}"
  register: _rf_boot_disable
  no_log: "{{ oob_redfish_control_no_log }}"
