---
oob_redfish_control_baseuri: "{{ vars.get('oob_baseuri', inventory_hostname) }}"
oob_redfish_control_user: "{{ vars.get('oob_user', '') }}"
oob_redfish_control_password: "{{ vars.get('oob_password', '') }}"

oob_redfish_control_validate_certs: "{{ vars.get('oob_validate_certs', false) | bool }}"
oob_redfish_control_ca_path: "{{ vars.get('oob_ca_path', '') }}"
oob_redfish_control_timeout: "{{ vars.get('oob_timeout', 60) | int }}"

# Security / logging
oob_redfish_control_no_log: "{{ vars.get('oob_no_log', true) | bool }}"
oob_redfish_control_debug: "{{ vars.get('oob_debug', false) | bool }}"

# Actions (set what you need; role executes the provided ones)
oob_redfish_control_power_action: "{{ vars.get('oob_power_action', '') }}"
oob_redfish_control_power_wait: "{{ vars.get('oob_power_wait', false) | bool }}"
oob_redfish_control_power_wait_timeout: "{{ vars.get('oob_power_wait_timeout', 120) | int }}"

oob_redfish_control_boot_target: "{{ vars.get('oob_boot_target', '') }}"
oob_redfish_control_boot_override_mode: "{{ vars.get('oob_boot_override_mode', 'UEFI') }}"
oob_redfish_control_boot_persistent: "{{ vars.get('oob_boot_persistent', false) | bool }}"
oob_redfish_control_boot_next: "{{ vars.get('oob_boot_next', '') }}"
oob_redfish_control_uefi_target: "{{ vars.get('oob_uefi_target', '') }}"
oob_redfish_control_boot_disable_override: "{{ vars.get('oob_boot_disable_override', false) | bool }}"

oob_redfish_control_virtual_media_action: "{{ vars.get('oob_virtual_media_action', '') }}"
oob_redfish_control_virtual_media_category: "{{ vars.get('oob_virtual_media_category', 'Systems') }}"
oob_redfish_control_virtual_media_image_url: "{{ vars.get('oob_virtual_media_image_url', '') }}"
oob_redfish_control_virtual_media_base_url: "{{ vars.get('oob_virtual_media_base_url', '') }}"
oob_redfish_control_virtual_media_image: "{{ vars.get('oob_virtual_media_image', '') }}"
oob_redfish_control_virtual_media_media_types: "{{ vars.get('oob_virtual_media_media_types', ['CD', 'DVD']) }}"
oob_redfish_control_virtual_media_username: "{{ vars.get('oob_virtual_media_username', '') }}"
oob_redfish_control_virtual_media_password: "{{ vars.get('oob_virtual_media_password', '') }}"
oob_redfish_control_virtual_media_transfer_protocol_type: >-
  "{{ vars.get('oob_virtual_media_transfer_protocol_type', '') }}"
oob_redfish_control_virtual_media_transfer_method: "{{ vars.get('oob_virtual_media_transfer_method', '') }}"
oob_redfish_control_virtual_media_write_protected: "{{ vars.get('oob_virtual_media_write_protected', true) | bool }}"
oob_redfish_control_virtual_media_inserted: "{{ vars.get('oob_virtual_media_inserted', true) | bool }}"

# IDs (usually set by oob_redfish_inventory; if "auto"/undefined, control role will include inventory role)
oob_redfish_control_system_id: "{{ vars.get('oob_system_id', 'auto') }}"
oob_redfish_control_manager_id: "{{ vars.get('oob_manager_id', 'auto') }}"
oob_redfish_control_chassis_id: "{{ vars.get('oob_chassis_id', 'auto') }}"
