---
net_vlan_autogen_enabled: true
net_vlan_autogen_overwrite: false

net_vlan_autogen_wan_connection_name: "wan"
net_vlan_autogen_admin_connection_name: "admin"
net_vlan_autogen_trunk_connection_name: "trunk-parent"

net_vlan_autogen_trunk_parent_state: "present"
