---
argument_specs:
  main:
    short_description: Discover Redfish IDs and basic inventory.
    options:
      oob_redfish_inventory_baseuri:
        type: str
        required: false
      oob_redfish_inventory_user:
        type: str
        required: true
      oob_redfish_inventory_password:
        type: str
        required: true
      oob_redfish_inventory_validate_certs:
        type: bool
        default: false
      oob_redfish_inventory_ca_path:
        type: str
        required: false
      oob_redfish_inventory_timeout:
        type: int
        default: 60
      oob_redfish_inventory_check_availability:
        type: bool
        default: true
      oob_redfish_inventory_system_id:
        type: str
        default: "auto"
      oob_redfish_inventory_manager_id:
        type: str
        default: "auto"
      oob_redfish_inventory_chassis_id:
        type: str
        default: "auto"
      oob_redfish_inventory_no_log:
        type: bool
        default: true
      oob_redfish_inventory_debug:
        type: bool
        default: false
