---
- name: assert | Test all variable are defined
  ansible.builtin.assert:
    that:
      - terragrunt_http_username is defined
      - terragrunt_http_username | length > 0
      - terragrunt_http_password is defined
      - terragrunt_http_password | length > 0
    quiet: true
