---
opnsense_api_key: ""
opnsense_api_secret: ""
opnsense_api_validate_certs: false
opnsense_api_port: 443
opnsense_ssh_port: 22
opnsense_ssh_wait_timeout: 300
opnsense_api_wait_timeout: 300

# Rendered XML content to deploy to /conf/config.xml
opnsense_config_xml: ""

# Template path (relative to role)
opnsense_config_template: "config.xml.j2"
