---
galaxy_info:
  author: Dirk Egert
  description: Role to create custom terragrunt environments
  company: degert-it
  license: license (BSD, MIT)
  min_ansible_version: '2.8'
  role_name: terragrunt
  namespace: default
  galaxy_tags: []
dependencies: []
