---
galaxy_info:
  role_name: net_vlan_autogen
  namespace: lit
  author: Ren√© Osorio
  description: Generate NetworkManager network_connections + VLAN interface list from net_vlan_configs (facts only).
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - modulix
    - network
    - vlan
    - nmcli
    - rhel

dependencies: []
